name: 编译luci-app-tailscale

on:
  workflow_dispatch:
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载工具链
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          wget -qO /opt/sdk.tar.xz https://downloads.immortalwrt.org/releases/23.05.4/targets/x86/64/immortalwrt-sdk-23.05.4-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf /opt/sdk.tar.xz -C /opt
          cp -R ${{ github.workspace }} /opt/luci-app-tailscale
      - name: 开始编译
        run: |
          cd /opt/immortalwrt-sdk*/package
          cp -R /opt/luci-app-tailscale .
          cd /opt/immortalwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
          cd /opt/immortalwrt-sdk*
          make package/luci-app-tailscale/compile V=s -j1
          cd /opt/immortalwrt-sdk*/bin/packages/*/base
          ls
          mv *.ipk /opt/luci-app-tailscale_1.2.3_all.ipk
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-tailscale
          path: /opt/luci-app-tailscale_1.2.3_all.ipk
